// Generated by the same table that builds the CLI command tree: one description per
// Runtime command, keyed by the name in the request union. Adding a command to
// `runtimeRequestSchema` without adding it here is a compile error.
import type { RuntimeRequest } from './index.js';

export interface RuntimeCommandInfo {
  /** The versioned command name, exactly as `runtimeRequestSchema` spells it. */
  readonly command: RuntimeRequest['command'];
  /** The CLI group a user finds it under. */
  readonly group: string;
  /** One line: what this command is for. */
  readonly summary: string;
}

export const runtimeCommandSummaries = {
  "agent.config.clear": {
    command: "agent.config.clear",
    group: "agent",
    summary: "清掉某一层（全局或某项目）的 Agent 配置覆盖",
  },
  "agent.config.get": {
    command: "agent.config.get",
    group: "agent",
    summary: "读生效中的 Agent 配置及其来源层（环境变量 > 项目 > 全局 > 适配器默认）",
  },
  "agent.config.set": {
    command: "agent.config.set",
    group: "agent",
    summary: "写一层 Agent 配置；只影响新 Session，生效值随 Execution 记录",
  },
  "agent.plugins.list": {
    command: "agent.plugins.list",
    group: "agent",
    summary: "只读检测可选的 extensions / skills / prompt templates / themes",
  },
  "attention.answer": {
    command: "attention.answer",
    group: "attention",
    summary: "回答一条 Attention（confirm / value / cancel / 结构化问卷）",
  },
  "attention.list": {
    command: "attention.list",
    group: "attention",
    summary: "列出项目当前打开的 Attention",
  },
  "attention.resolve": {
    command: "attention.resolve",
    group: "attention",
    summary: "收口一条没有 provider dialog 的等待（散文提问）：--dismiss 或 --answer",
  },
  "events.list": {
    command: "events.list",
    group: "events",
    summary: "按游标读一批领域事件",
  },
  "events.subscribe": {
    command: "events.subscribe",
    group: "events",
    summary: "持续跟随领域事件流",
  },
  "intent.send": {
    command: "intent.send",
    group: "intent",
    summary: "把自然语言意图发给某个 Service；创建一个 Intention Process（解释属 S6）",
  },
  "permission.get": {
    command: "permission.get",
    group: "settings",
    summary: "读当前权限模式及其默认值",
  },
  "permission.set": {
    command: "permission.set",
    group: "settings",
    summary: "切换权限模式（无确认）",
  },
  "process.get": {
    command: "process.get",
    group: "process",
    summary: "按 id 读一个 Process 的 kind/状态/parent Service 与关联 Execution",
  },
  "process.input": {
    command: "process.input",
    group: "process",
    summary: "向运行中的 Process 追加输入（复用 Session Guidance 通道）",
  },
  "process.list": {
    command: "process.list",
    group: "process",
    summary: "列出 Process（可按 parent Service 与状态过滤）",
  },
  "process.pause": {
    command: "process.pause",
    group: "process",
    summary: "暂停一个 Development Process（复用 Task 协作停止）",
  },
  "process.resume": {
    command: "process.resume",
    group: "process",
    summary: "恢复已暂停的 Process（新建 Execution 并以 provider conversation 续接）",
  },
  "process.terminate": {
    command: "process.terminate",
    group: "process",
    summary: "终止一个 Process（终态，不自动重开）",
  },
  "project.impact.explain": {
    command: "project.impact.explain",
    group: "project",
    summary: "解释某 Task 相对活动集合的判定（SAFE / UNKNOWN / CONFLICTING）",
  },
  "project.impact.show": {
    command: "project.impact.show",
    group: "project",
    summary: "读回某个 Task 已记录的 ImpactSnapshot",
  },
  "project.impact.validate": {
    command: "project.impact.validate",
    group: "project",
    summary: "报告影响映射是否存在、是否为已确认的那一份",
  },
  "project.inspect": {
    command: "project.inspect",
    group: "project",
    summary: "看一个项目文件夹的仓库身份，并说明建 Task workspace 时的基线",
  },
  "project.knowledge.list": {
    command: "project.knowledge.list",
    group: "project",
    summary: "列出项目知识层的条目与来源",
  },
  "project.knowledge.resolve": {
    command: "project.knowledge.resolve",
    group: "project",
    summary: "报告某 Task 的下一个 Execution 会用到什么知识，且不启动它",
  },
  "project.knowledge.show": {
    command: "project.knowledge.show",
    group: "project",
    summary: "读回某个已记录的 Execution 知识快照",
  },
  "project.knowledge.validate": {
    command: "project.knowledge.validate",
    group: "project",
    summary: "逐条报告知识层被拒的条目（有拒条目时整层不出快照）",
  },
  "project.list": {
    command: "project.list",
    group: "project",
    summary: "列出已注册（trust）的项目",
  },
  "project.trust": {
    command: "project.trust",
    group: "project",
    summary: "把一个项目文件夹接入本 Runtime（FULL 下零确认）",
  },
  "project.verificationPolicy": {
    command: "project.verificationPolicy",
    group: "project",
    summary: "读该项目 main ref 上的人工验证策略",
  },
  "reclaim.apply": {
    command: "reclaim.apply",
    group: "reclaim",
    summary: "真正回收（只删归属校验通过的三类资源，默认保留失败现场）",
  },
  "reclaim.plan": {
    command: "reclaim.plan",
    group: "reclaim",
    summary: "只读干跑：列出会被回收的资源，不删任何东西",
  },
  "reclaim.records": {
    command: "reclaim.records",
    group: "reclaim",
    summary: "读 append-only 的回收账本",
  },
  "runtime.commands": {
    command: "runtime.commands",
    group: "runtime",
    summary: "列出 Runtime 的每一条 versioned 命令及其大致功能范围",
  },
  "runtime.ping": {
    command: "runtime.ping",
    group: "status",
    summary: "报告本 Runtime 的状态与所有权证据（必要时先拉起 Runtime）",
  },
  "runtime.stop": {
    command: "runtime.stop",
    group: "stop",
    summary: "请求本 home 的 Runtime 停机，并按 pid + start token 核验它真的退出",
  },
  "scheduler.capacity.get": {
    command: "scheduler.capacity.get",
    group: "scheduler",
    summary: "读这条唯一上限、它的来源、当前占用者与放行/等待原因码",
  },
  "scheduler.capacity.reset": {
    command: "scheduler.capacity.reset",
    group: "scheduler",
    summary: "删除显式上限，回到文档默认值",
  },
  "scheduler.capacity.set": {
    command: "scheduler.capacity.set",
    group: "scheduler",
    summary: "写这条唯一上限（零确认、写后读回、幂等）",
  },
  "scheduler.control.pause": {
    command: "scheduler.control.pause",
    group: "scheduler",
    summary: "冻结模型驱动：持久化屏障后按 pid + start token + incarnation 核验冻结",
  },
  "scheduler.control.reconcile": {
    command: "scheduler.control.reconcile",
    group: "scheduler",
    summary: "按观察对账冻结目标（不发信号、不改写 Task 生命周期状态）",
  },
  "scheduler.control.resume": {
    command: "scheduler.control.resume",
    group: "scheduler",
    summary: "解除冻结（只有显式继续才会解除）",
  },
  "scheduler.control.status": {
    command: "scheduler.control.status",
    group: "scheduler",
    summary: "读全局控制状态与每个冻结目标的核验事实",
  },
  "scheduler.reservations.acquire": {
    command: "scheduler.reservations.acquire",
    group: "scheduler",
    summary: "在一个事务里重核版本/依赖/快照代际/容量后记录一条预留",
  },
  "scheduler.reservations.get": {
    command: "scheduler.reservations.get",
    group: "scheduler",
    summary: "按 reservation-id 读回一条预留及其历史",
  },
  "scheduler.reservations.list": {
    command: "scheduler.reservations.list",
    group: "scheduler",
    summary: "列出项目的活动预留及其持有者证据与历史",
  },
  "scheduler.reservations.reconcile": {
    command: "scheduler.reservations.reconcile",
    group: "scheduler",
    summary: "把每条活动预留的持有者与真实进程表对账（能证明已消失才释放）",
  },
  "scheduler.reservations.release": {
    command: "scheduler.reservations.release",
    group: "scheduler",
    summary: "显式释放一条预留（必须给 --reason）",
  },
  "scheduler.reservations.workspace.prepare": {
    command: "scheduler.reservations.workspace.prepare",
    group: "scheduler",
    summary: "为一条预留准备并绑定 Task 工作树",
  },
  "service.get": {
    command: "service.get",
    group: "service",
    summary: "按 id 读一个 Service 的 kind/lifecycle/core 投影与 metadata",
  },
  "service.list": {
    command: "service.list",
    group: "service",
    summary: "列出 Service（可按 kind 与 parent 过滤；--all 含 RETIRED）",
  },
  "service.state.get": {
    command: "service.state.get",
    group: "service",
    summary: "读一个 Service 的 core 投影、metadata 与 state/core version",
  },
  "service.state.set": {
    command: "service.state.set",
    group: "service",
    summary: "以 expected version CAS 写一条 namespaced metadata",
  },
  "service.tree": {
    command: "service.tree",
    group: "service",
    summary: "打印以某个 Service 为根的子树（默认 root Service）",
  },
  "session.guidance.get": {
    command: "session.guidance.get",
    group: "session",
    summary: "按 guidance-id 读回一条 guidance 及其执行绑定",
  },
  "session.guidance.list": {
    command: "session.guidance.list",
    group: "session",
    summary: "列出某 Task 的 guidance 记录与投递尝试",
  },
  "session.guidance.record": {
    command: "session.guidance.record",
    group: "session",
    summary: "投递一条 Session Guidance：立即影响当前执行，但不产生 TaskRevision",
  },
  "session.handoff.admit": {
    command: "session.handoff.admit",
    group: "session",
    summary: "真正启动 successor（PTY 原生终端或 RPC provider），并移动 lease",
  },
  "session.handoff.attach": {
    command: "session.handoff.attach",
    group: "session",
    summary: "接入原生终端流（最多一个写者；detach 不终止终端与 provider）",
  },
  "session.handoff.cancel": {
    command: "session.handoff.cancel",
    group: "session",
    summary: "取消一次交接请求",
  },
  "session.handoff.detach": {
    command: "session.handoff.detach",
    group: "session",
    summary: "离开原生终端，保留终端与 provider 继续运行",
  },
  "session.handoff.release": {
    command: "session.handoff.release",
    group: "session",
    summary: "交还给自动化：写 release 字节、核验 provider 已退出、复用同一会话文件",
  },
  "session.handoff.request": {
    command: "session.handoff.request",
    group: "session",
    summary: "记录一次交接请求（takeover 或 return）",
  },
  "session.handoff.status": {
    command: "session.handoff.status",
    group: "session",
    summary: "读回交接状态：incarnation 历史、writer lease、fence 与接纳判定",
  },
  "session.handoff.terminal.read": {
    command: "session.handoff.terminal.read",
    group: "session",
    summary: "从游标读终端输出",
  },
  "session.handoff.terminal.resize": {
    command: "session.handoff.terminal.resize",
    group: "session",
    summary: "调整终端尺寸（作用在 slave fd 上的 stty）",
  },
  "session.handoff.terminal.write": {
    command: "session.handoff.terminal.write",
    group: "session",
    summary: "向终端写文本",
  },
  "session.handoff.writer.acquire": {
    command: "session.handoff.writer.acquire",
    group: "session",
    summary: "申请 writer lease（已被占用则 ATTACHMENT_BUSY 退 1）",
  },
  "session.handoff.writer.release": {
    command: "session.handoff.writer.release",
    group: "session",
    summary: "释放 writer lease",
  },
  "session.transcript": {
    command: "session.transcript",
    group: "session",
    summary: "只读展示某个 Session 的 provider 转写（工具调用、助手文本、thinking、用量）",
  },
  "session.transcript.part": {
    command: "session.transcript.part",
    group: "session",
    summary: "读回转写中某一条目的某一段完整内容",
  },
  "settings.list": {
    command: "settings.list",
    group: "settings",
    summary: "总览当前启用中的全部 Runtime 级设置（只读、零确认）",
  },
  "settings.proseQuestionAttention.get": {
    command: "settings.proseQuestionAttention.get",
    group: "settings",
    summary: "散文提问是否升级为等待：auto（默认）/ record-only / off",
  },
  "settings.proseQuestionAttention.set": {
    command: "settings.proseQuestionAttention.set",
    group: "settings",
    summary: "散文提问是否升级为等待：auto（默认）/ record-only / off",
  },
  "signal.get": {
    command: "signal.get",
    group: "signal",
    summary: "按 id 读一条 Signal 及其 attempts 与幂等回执",
  },
  "signal.list": {
    command: "signal.list",
    group: "signal",
    summary: "列出 Signal（可按目标 Service、state、kind 过滤）",
  },
  "signal.retry": {
    command: "signal.retry",
    group: "signal",
    summary: "显式重试一条 RETRYABLE/DEAD_LETTER/RECOVERY_REQUIRED 的 Signal",
  },
  "signal.send": {
    command: "signal.send",
    group: "signal",
    summary: "向某个 Service 发一条 Signal；payload 通过该 Service 的 contract 校验",
  },
  "task.archive": {
    command: "task.archive",
    group: "task",
    summary: "归档（软删除：只写 archived_at，默认列表隐藏）",
  },
  "task.cancel": {
    command: "task.cancel",
    group: "task",
    summary: "终止任务（终态 CANCELLED，不自动重开，审计与证据保留）",
  },
  "task.create": {
    command: "task.create",
    group: "task",
    summary: "新建 Task（三个必填字段：显示标题、命名标题、任务详情）",
  },
  "task.depends.add": {
    command: "task.depends.add",
    group: "task",
    summary: "增加一条依赖（写入前检测环，失败不部分应用）",
  },
  "task.depends.list": {
    command: "task.depends.list",
    group: "task",
    summary: "列出依赖关系，以及上游 result commit 是否对基线可达",
  },
  "task.depends.remove": {
    command: "task.depends.remove",
    group: "task",
    summary: "删除一条依赖",
  },
  "task.list": {
    command: "task.list",
    group: "task",
    summary: "列出项目的 Task（--all 含已归档）",
  },
  "task.operation.cancel": {
    command: "task.operation.cancel",
    group: "task",
    summary: "取消一个 Operation（先确认进程静止，未确认则 RECONCILE_REQUIRED）",
  },
  "task.operation.get": {
    command: "task.operation.get",
    group: "task",
    summary: "按 operation-id 读回一个 Operation 的步骤级进度",
  },
  "task.operation.list": {
    command: "task.operation.list",
    group: "task",
    summary: "列出某 Task 的 Operation",
  },
  "task.pause": {
    command: "task.pause",
    group: "task",
    summary: "协作暂停：确认 provider 已退出后才落 PAUSED，保留工作树与会话证据",
  },
  "task.purge": {
    command: "task.purge",
    group: "task",
    summary: "永久删除任务及其资源（唯一显式 --yes，不在任何常态路径上）",
  },
  "task.recover": {
    command: "task.recover",
    group: "task",
    summary: "对 RECOVERY_REQUIRED 任务按事实对账，只在能证明 provider 已消失时收口",
  },
  "task.result.capture": {
    command: "task.result.capture",
    group: "task",
    summary: "FULL 下的单步成果提交（不确认、不应用敏感路径拒绝）",
  },
  "task.result.commit": {
    command: "task.result.commit",
    group: "task",
    summary: "STRICT 下的两步成果提交第二步：带 authorization-id 确认提交",
  },
  "task.result.prepare": {
    command: "task.result.prepare",
    group: "task",
    summary: "STRICT 下的两步成果提交第一步：准备并固定差异",
  },
  "task.resume": {
    command: "task.resume",
    group: "task",
    summary: "在同一工作树新建 Execution，并以 provider conversation resume 继续",
  },
  "task.retry": {
    command: "task.retry",
    group: "task",
    summary: "重新排队一个 FAILED Task（绝不自动重试）；新 Execution 走同一道门",
  },
  "task.revision.create": {
    command: "task.revision.create",
    group: "task",
    summary: "新建一条 TaskRevision（改任务详情或功能声明）",
  },
  "task.revision.delivery.get": {
    command: "task.revision.delivery.get",
    group: "task",
    summary: "按 delivery-id 读回一次投递",
  },
  "task.revision.delivery.list": {
    command: "task.revision.delivery.list",
    group: "task",
    summary: "列出某 Task 的修订投递及其状态",
  },
  "task.revision.delivery.resolve": {
    command: "task.revision.delivery.resolve",
    group: "task",
    summary: "对一次投递做显式收口（结构化 ACK 或经核验的 successor）",
  },
  "task.revision.list": {
    command: "task.revision.list",
    group: "task",
    summary: "列出某 Task 的修订历史",
  },
  "task.run": {
    command: "task.run",
    group: "task",
    summary: "显式请求启动一次执行；与自动调度走同一道门（依赖/冲突/容量）",
  },
  "task.schedule.clearUnknown": {
    command: "task.schedule.clearUnknown",
    group: "task",
    summary: "记录一次对 UNKNOWN 判定的显式单次放行（不改写已记录的判定）",
  },
  "task.schedule.explain": {
    command: "task.schedule.explain",
    group: "task",
    summary: "解释某 Task 现在为什么没在跑（依赖判定、冲突判定、容量）",
  },
  "task.schedule.plan": {
    command: "task.schedule.plan",
    group: "task",
    summary: "按候选顺序干跑一遍，不预留也不启动任何东西",
  },
  "task.schedule.run": {
    command: "task.schedule.run",
    group: "task",
    summary: "请求一趟调度 pass（与事件触发、周期恢复用的是同一个循环）",
  },
  "task.schedule.status": {
    command: "task.schedule.status",
    group: "task",
    summary: "报告调度事实：活动集合、占用、最近一趟 pass",
  },
  "task.status": {
    command: "task.status",
    group: "task",
    summary: "读回一个 Task 的完整投影（含 Execution、Session 与等待原因）",
  },
  "task.submit": {
    command: "task.submit",
    group: "task",
    summary: "把 DRAFT Task 提交为 READY，进入调度",
  },
  "task.tests.history": {
    command: "task.tests.history",
    group: "task",
    summary: "列出该计划的 append-only 历史",
  },
  "task.tests.record": {
    command: "task.tests.record",
    group: "task",
    summary: "把当前 tests.json 快照成绑定 (task, revision, commit, digest) 的记录",
  },
  "task.tests.show": {
    command: "task.tests.show",
    group: "task",
    summary: "读回当前生效的定向测试计划",
  },
  "task.unarchive": {
    command: "task.unarchive",
    group: "task",
    summary: "取消归档",
  },
  "task.verification.list": {
    command: "task.verification.list",
    group: "task",
    summary: "列出某 Task 的验证记录（含绑定 revision/commit/policy digest）",
  },
  "task.verify": {
    command: "task.verify",
    group: "task",
    summary: "在固定 commit 的隔离副本上运行验证策略，并记录绑定 revision/commit 的证据",
  },
} as const satisfies Record<RuntimeRequest['command'], RuntimeCommandInfo>;

